#pragma once
#include "GonEngine/renderer/system/render_manager.hpp"
#include "GonEngine/renderer/cameras/camera_manager.hpp"
#include "GonEngine/platform/OpenGL/opengl_shader.hpp"
#include "GonEngine/platform/OpenGL/opengl_vao.hpp"
#include "GonEngine/gameobjects/gameobject.hpp"
#include "GonEngine/geometries/triangle.hpp"
#include "GonEngine/geometries/quad.hpp"
#include "GonEngine/renderer/renderer.hpp"
#include <glm/gtc/matrix_transform.hpp>
#include "GonEngine/events/events.hpp"
#include "GonEngine/memcfg/goncfg.h"
#include "GonEngine/gon.hpp"
#include "GonEngine/log.hpp"
#include <glm/glm.hpp>
#include <imgui.h>

#include <glm/gtc/type_ptr.hpp>
#include "GonEngine/platform/OpenGL/opengl_texture.hpp"
